# Generated by Django 4.2.6 on 2023-10-09 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_reservations_ticket_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='ticket_number',
            field=models.CharField(max_length=9),
        ),
    ]
