# Generated by Django 4.2.6 on 2023-10-09 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_reservations_ticket_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='ticket_number',
            field=models.CharField(editable=False, max_length=9, unique=True),
        ),
    ]
