# Generated by Django 4.2.6 on 2023-10-10 15:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_reservations_ticket_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
