# Generated by Django 4.2.6 on 2023-10-17 23:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_reservations_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 10, 18, 0, 4, 25, 274288)),
        ),
    ]
