# Generated by Django 4.2.6 on 2023-11-06 07:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_alter_reservations_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='email',
            field=models.EmailField(default='example@anymail.com', max_length=200),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 11, 6, 8, 20, 3, 38206)),
        ),
    ]
