# Generated by Django 4.2.6 on 2023-11-12 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_reservations_email_alter_reservations_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 11, 12, 12, 11, 49, 928991)),
        ),
    ]
