# Generated by Django 4.2.6 on 2023-11-12 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_alter_reservations_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
